apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops-project
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk   # rootpassword â†’ base64
  MYSQL_DATABASE: YXBwZGJf               # appdb
  MYSQL_USER: YXBwdXNlcg==               # appuser
  MYSQL_PASSWORD: YXBwcGFzc3dvcmQ=       # apppassword
